### ISSUE TITLE
RuntimeError: Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same

### ISSUE THREAD

**Issue by wuxiaolianggit** [crissallan/Skeleton_Aware_Networks_for_Deep_Motion_Retargeting#1]
Excuse me, how to solve this problem？

Traceback (most recent call last):
  File "inference.py", line 94, in <module>
    s_latent_a = static_enc_a(static_a)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/slowfast/Skeleton_Aware_Networks_for_Deep_Motion_Retargeting/model/enc_and_dec.py", line 211, in forward
    out = self.enc_layer(x)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/slowfast/Skeleton_Aware_Networks_for_Deep_Motion_Retargeting/model/enc_and_dec.py", line 47, in forward
    identity = self.conv1by1(x)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 349, in forward
    return self._conv_forward(input, self.weight)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 346, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same

@crissallan

**Comment by ANYMS-A** [comment]
It seems that you didn't move the input tensor to the GPU. The tensor on the GPU is torch.cuda.FloatTensor
